# Generated by Django 4.2.9 on 2024-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=50)),
                ("employee_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PresentEmployeeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("present_count", models.IntegerField(default=0)),
            ],
        ),
    ]
