# Generated by Django 4.2.9 on 2024-01-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emp_management", "0001_initial"),
        ("reporting_management", "0002_employeereport_delete_departmentcount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50)),
                ("present_count", models.IntegerField(default=0)),
                ("absent_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50)),
                ("employee_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emp_management.employee",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EmployeeReport",
        ),
    ]
