# Generated by Django 4.2.9 on 2024-01-21 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_management", "0002_alter_employee_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_joining__lt", datetime.date(2024, 1, 21))),
                name="date_of_joining_must_be_less_than_current_date",
            ),
        ),
    ]
